In [1]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv('OPENAI_API_KEY')

In [4]:
model_client = OpenAIChatCompletionClient(model='gpt-4o',api_key=api_key)
agent_1 = AssistantAgent(name='my_assistant',model_client=model_client)
result = await agent_1.run(task='Tell me something about you?')
result

messages=[TextMessage(id='2a633cb5-b0f7-4044-8255-553e952f2f77', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 6, 6, 47, 43, 896125, tzinfo=datetime.timezone.utc), content='Tell me something about you?', type='TextMessage'), TextMessage(id='6a28915c-5dd3-4d70-af1a-deb38ae983a6', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=63), metadata={}, created_at=datetime.datetime(2025, 7, 6, 6, 47, 46, 244285, tzinfo=datetime.timezone.utc), content='I am an AI language model trained by OpenAI, here to assist you with a wide variety of questions and tasks. I can provide information, answer queries, help you learn new things, and perform certain tasks to the best of my abilities. Is there anything specific you would like to know or do? TERMINATE', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='2a633cb5-b0f7-4044-8255-553e952f2f77', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 6, 6, 47, 43, 896125, tzinfo=datetime.timezone.utc), content='Tell me something about you?', type='TextMessage'), TextMessage(id='6a28915c-5dd3-4d70-af1a-deb38ae983a6', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=63), metadata={}, created_at=datetime.datetime(2025, 7, 6, 6, 47, 46, 244285, tzinfo=datetime.timezone.utc), content='I am an AI language model trained by OpenAI, here to assist you with a wide variety of questions and tasks. I can provide information, answer queries, help you learn new things, and perform certain tasks to the best of my abilities. Is there anything specific you would like to know or do? TERMINATE', type='TextMessage')] stop_reason=None
